### ISSUE TITLE
AutocompleteFilter

### ISSUE THREAD

**Issue by cmarfil** [Logicify/jquery-locationpicker-plugin#82]
Hello, 

It's possible to include a filter for search? for example search only in a specific city to get better results.

Some docs:
https://developers.google.com/android/reference/com/google/android/gms/location/places/AutocompleteFilter
http://stackoverflow.com/questions/8282026/how-to-limit-google-autocomplete-results-to-city-and-country-only

Thanks!

**Comment by Sumragen** [comment]
@cmarfil Hi! Your issue is the same with #75. 
When [development](https://github.com/Logicify/jquery-locationpicker-plugin/tree/development) branch will be merged with **master** it can be possible to use. Also you can temporary use [development](https://github.com/Logicify/jquery-locationpicker-plugin/tree/development) branch.
